FROM ubuntu
RUN apt-get update && apt install openjdk-11-jdk -y
ADD https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.96/bin/apache-tomcat-8.5.96.tar.gz ./
RUN tar -xf apache-tomcat-8.5.96.tar.gz -C /opt
WORKDIR /opt/apache-tomcat-8.5.96
COPY student.war webapps/student.war
COPY mysql-connector.jar lib/mysql-connector.jar
COPY context.xml conf/context.xml
WORKDIR ./bin
EXPOSE 8080
CMD ["./catalina.sh","run"]

