FROM ubuntu
RUN apt update && apt install apache2 -y
ADD index.html /var/www/html/index.html
RUN chmod -R 777 /var/www/html
COPY proxy.conf /etc/apache2/sites-available/proxy.conf
RUN a2ensite proxy.conf
RUN a2enmod proxy proxy_http
EXPOSE 80
CMD ["apache2ctl", "-D", "FOREGROUND"]
